apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: bert-fine-tuning-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22, pipelines.kubeflow.org/pipeline_compilation_time: '2024-03-18T11:45:23.182881',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "A pipeline that fine-tunes
      bert model with sprecific data.", "name": "bert Fine-Tuning Pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22}
spec:
  entrypoint: bert-fine-tuning-pipeline
  templates:
  - name: bert-fine-tuning-pipeline
    dag:
      tasks:
      - {name: data-preprocessing, template: data-preprocessing}
      - name: fine-tuned-model-evaluation
        template: fine-tuned-model-evaluation
        dependencies: [output-after-fine-tuning]
      - name: output-after-fine-tuning
        template: output-after-fine-tuning
        dependencies: [data-preprocessing]
      - name: output-before-fine-tuning
        template: output-before-fine-tuning
        dependencies: [data-preprocessing]
  - name: data-preprocessing
    container:
      args: []
      command: [python3, /app/Preprocess_data/preprocess_data.py]
      image: maamounm/llm_pipeline:latest
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: fine-tuned-model-evaluation
    container:
      command: [python3, /app/evaluate_fine_tuned_model/evaluate_fine_tuned_model.py]
      image: maamounm/llm_pipeline:latest
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: output-after-fine-tuning
    container:
      command: [python3, /app/Fine_tuned_model_output/fine_tuned_model_output.py]
      image: maamounm/llm_pipeline:latest
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: output-before-fine-tuning
    container:
      command: [python3, /app/Model_output/model_output.py]
      image: maamounm/llm_pipeline:latest
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
